name: build-website

on:
  workflow_call:

jobs:
  build-application:
    name: Build application
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1
    
    - name: Build publishable website
      run: |
        dotnet publish --configuration Release  -o publish2
      working-directory: ./src/ToyCompany/ToyCompany.Website

    - name: Zip publishable website
      run: |
        zip -r publish.zip
      working-directory: ./src/ToyCompany/ToyCompany.Website/

    - name: Upload website as workflow artifact
      uses: actions/upload-artifact@v3
      with: 
        name: website
        path: ./src/ToyCompany/ToyCompany.Website/bin/Release/netcoreapp3.1/publish/publish.zip
